templates/kraken/kraken.ini.jinja

for this we use the log4cplus's NDC
Merge this one only after the next deployment in production.

In kraken's log we replace the thread id by the request ID of jormungandr

---

fabfile/env/platforms.py
templates/jormungandr/settings.py.jinja

old REDIS_* weren't used anymore

Add the possibility to use redis as backend for jormungandr cache

---

fabfile/component/db.py
fabfile/component/kraken.py
fabfile/component/tyr.py
fabfile/env/platforms.py
fabfile/tasks.py
templates/db/rename_postgresql_database_user.sql.jinja
templates/db/rename_tyr_jormungandr_database.sql.jinja

"remove_instance" task and "rename_instance" task did not work. A refacto of "remove_instance" task impact the "rename_instance" task.
I do a refacto for the "remove_instance" task and I will do in an other branch the refacto for the "rename_instance" task.

refacto remove_instance method

---

fabfile/component/db.py
fabfile/component/tyr.py
fabfile/env/platforms.py
fabfile/tasks.py
templates/tyr/cities_alembic.ini.jinja
templates/tyr/settings.py.jinja

cities was not install by default on fabric.

Cities integration refacto

---

fabfile/env/configuration_example.py
fabfile/env/platforms.py

Configuration simple example.
All is installed on 2 servers:
* one for the data integration (addr_server_ed)
* one for the rest addr_server_kraken
If addr_server_kraken is not provided, all is installed on addr_server_ed

add one example for configuration file

---

fabfile/component/jormungandr.py
fabfile/instance.py
templates/jormungandr/instance.json.jinja
templates/jormungandr/jormungandr.ini.jinja

needed to handle realtime proxies
clean up some deprecated code in the same time
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canaltp/fabric_navitia/87)
don't forget to merge https://github.com/CanalTP/navitia_deployment_conf/pull/95 after
@kinnou02 @Hoshiyo can you review this ? it would be nice to test the deployment tonight. (or tomorrow)

change jormun instances conf from ini to json

---

fabfile/component/jormungandr.py
fabfile/component/tyr.py

It will be needed with the upgrade of flask_restful

we want to upgrade pip packages if the version in the requirements change

---

fabfile/env/platforms.py
templates/jormungandr/settings.py.jinja

needed by https://github.com/CanalTP/navitia/pull/1472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/canaltp/fabric_navitia/97)

Add cache by default and handle timeo's timeout

---

fabfile/component/tyr.py
fabfile/tasks.py

in deploy_from_scratch, the configuration was not deployed at the right time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canaltp/fabric_navitia/104)

fix tyr configuration deployement

---

fabfile/component/kraken.py

added task require_kraken_started, good for tests
some refactoring too

added task require_kraken_started, some refactoring

---

fabfile/component/kraken.py

for the case where len(instance.kraken_engines) > 1

fix create_eng_instance

---

fabfile/component/kraken.py
fabfile/instance.py

this has not been seen so far, wich is strange, but it crashed last internal deployment

fix test_kraken for the case hosts parameter is like user@url

---

fabfile/component/kraken.py
fabfile/component/tyr.py
fabfile/utils.py

one case of squared roles, some redundant executions, symlink should be idempotent too

fix some tyr tasks after integration tests

---

fabfile/component/tyr.py

fix create_tyr_instance and remove_tyr_instance

---

fabfile/component/kraken.py

tested with integration test framework

devops458 restart kraken even if it has no data

---

fabfile/component/kraken.py

add a check_kraken_data_synchronization
that for all instances query all engines to check that they have the
same data loaded.
used to analyse the platform, it has to be called manually (for the
moment at least)

add some helper function to check data synchronization

---

templates/jormungandr/settings.py.jinja

**This has to be merge before the deployment in production**

socket timeout must be a float, not a string.

---

fabfile/component/kraken.py

tested with integration test framework

devops440 add a redeploy_kraken task and refactor create_eng_instance

---

README.md
fabfile/component/jormungandr.py
integration_tests/test_jormun/test_setup.py

devop532 refactor jormungandr coverage tasks, add integration tests

---

integration_tests/conftest.py
integration_tests/docker.py

this should contribute to get tests running on jenkins

add timeout and processes wait duration parameter to tests

---

fabfile/__init__.py
fabfile/component/jormungandr.py
fabfile/component/kraken.py
fabfile/env/platforms.py
fabfile/prod_tasks.py
fabfile/tasks.py
integration_tests/test_kraken/test_duplicated.py
integration_tests/test_tasks/test_duplicated.py

allow restart kraken to restart serially, ie no interruption of service

refactor restart_kraken and add tests, some refactor too

---

README.md
fabfile/component/kraken.py
fabfile/tasks.py
integration_tests/test_kraken/test_duplicated.py

aka http://jira.canaltp.fr/browse/DEVOP-412

add rollback to kraken tasks

---

fabfile/utils.py
integration_tests/platforms/single.py
integration_tests/test_utils/__init__.py
integration_tests/test_utils/test_utils.py

create downtime with new nagios

---

fabfile/prod_tasks.py
fabfile/tasks.py
integration_tests/test_tasks/test_duplicated.py

http://jira.canaltp.fr/browse/DEVOP-543

devop543 refactor prod deployment orchestration

---

fabfile/utils.py

Need to be merged before customer deployment

specify superuser to execute curl command

---

fabfile/component/tyr.py

Should not be merge before the release 2.12
Require: https://github.com/CanalTP/navitia/pull/1680

Use tyr workers for executing import_last_dataset

---

fabfile/component/tyr.py
fabfile/env/platforms.py
fabfile/tasks.py

this relaunch failed binarisations once

add optional check of failed binarisation

---

integration_tests/platforms/distributed.py
integration_tests/platforms/duplicated.py
integration_tests/test_kraken/test_duplicated.py
integration_tests/test_tasks/test_duplicated.py

fix and improve tasks tests

---

fabfile/component/kraken.py

http://jira.canaltp.fr/browse/DEVOP-645

add a progression indicator to restart_all_krakens

---

requirements.txt

http://jira.canaltp.fr/browse/DEVOP-643

bump requirements to Fabric3

---

fabfile/env/platforms.py
fabfile/tasks.py
fabfile/utils.py
integration_tests/test_tyr/test_setup.py

http://jira.canaltp.fr/browse/DEVOP-682

DEVOP-682: show diff when uploading config files

---

fabfile/component/jormungandr.py
fabfile/instance.py

This modification needs the modification of navitia_deployment_conf

fabfile: Modification to pass url of valhalla for street network

---

fabfile/component/tyr.py
fabfile/env/platforms.py
fabfile/instance.py
integration_tests/platforms/duplicated.py

http://jira.canaltp.fr/browse/DEVOP-748

[DEVOP-748] add optional bina parallelism level per instance

---

fabfile/utils.py

https://github.com/CanalTP/navitia_deployment_conf/pull/182
Le token de login expire à un moment et lors des déploiements les logs sont pollués de messages d'erreur qu'on devrait pas avoir si on avait pas le token en dur mais récupéré depuis la requête envoyée
http://jira.canaltp.fr/browse/DEVOP-758

parse token

---

fabfile/component/kraken.py

add pkg to install

---

fabfile/component/tyr.py

j'ai utilisé le hide parce que je sais pas trop si c'est util de voir ce qui en sort

verify if synonym exist

---

fabfile/component/tyr.py
fabfile/env/platforms.py
fabfile/tasks.py

ref: https://github.com/CanalTP/navitia_deployment_conf/pull/218

Restart webservice tyr

---

fabfile/env/platforms.py
templates/kraken/systemd_kraken.jinja

https://github.com/CanalTP/navitia_deployment_conf/pull/221 -> to be merge

auto-restart added for kraken

---

fabfile/component/kraken.py

systemd use .service extension for services

add extension

---

fabfile/component/jormungandr.py
fabfile/instance.py

this configuration will change the next release, it will be easier (no
bragi_url in the instance)

autocomplete per instance configuration

---

fabfile/prod_tasks.py
fabfile/tasks.py

Need to be merge before prod deployment 2.25.0

restart apache for jormun conf

---

fabfile/component/db.py
fabfile/tasks.py

check_last_dataset task stop deployment if there are missing datasets. It's better to resolve the problem without stopping deployment

refacto check_last_dataset task

---

fabfile/component/tyr.py
fabfile/custom_tasks.py
fabfile/env/platforms.py
templates/jormungandr/settings.py.jinja
templates/tyr/cities_alembic.ini.jinja
templates/tyr/ed_alembic.ini.jinja
templates/tyr/ed_settings.sh.jinja
templates/tyr/instance.ini.jinja
templates/tyr/settings.py.jinja

cf : https://github.com/CanalTP/navitia_deployment_conf/pull/253

use new cluster for jormun db

---

fabfile/component/jormungandr.py

"show" parameter print an absent key if right instances are to warn list

change element from warn_list

---

fabfile/component/jormungandr.py
fabfile/tasks.py

Please do not merge. We need to do some test with Anna

Add checking with technical url on jormung

---

fabfile/component/kraken.py
fabfile/env/platforms.py
fabfile/tasks.py

dans le cadre de ce ticket http://jira.canaltp.fr/browse/DEVOPP-120

check loaded instances

---

fabfile/component/db.py

https://jira.canaltp.fr/browse/DEVOP-1337

authorize read schema before tables

---

fabfile/component/tyr.py

https://jira.canaltp.fr/browse/DEVOP-1411

create a new set to avoid conflict to the bina set

---

fabfile/env/platforms.py
templates/jormungandr/settings.py.jinja

Option to enable Jormun log in JSON.

Add JSON type for Jormungandr logs DEVOPP-571

---

templates/jormungandr/settings.py.jinja

Adding block to setup log format

Adding flag for sending mail to syslog

---

templates/jormungandr/settings.py.jinja

Setting value extras var to null.
Testing on platform alpha for non regression

Setting empty value to var extras

---

fabfile/env/platforms.py
templates/jormungandr/settings.py.jinja

Adding configuration due to manual setting on ws Navitia for removing pooling queues to BDD.
This was defined on pgpool now.

Removing pool db on ws

---

requirements.txt

fabtools has now been moved to our CanalTp repo.

Update fabtools dependency

---

fabfile/component/haproxy.py
fabfile/prod_tasks.py
fabfile/tasks.py

https://jira.kisio.org/browse/DEVOPP-1205
Prepare delivry navitia 2 with haproxy instead of ADC

Adding function disable/enable kraken on haproxy during delivery navitia 2

---

fabfile/component/jormungandr.py
fabfile/env/platforms.py
templates/jormungandr/jormungandr.wsgi.jinja
templates/jormungandr/newrelic.ini.jinja

Previously it was done manually :(

Handle newrelic in fabric

---

templates/haproxy/haproxy.cfg

increase_maxconns_haproxy by jyc

increase_maxconns_haproxy

---

templates/jormungandr/settings.py.jinja

Follow-up of #258
I forgot to update jormungandr configuration...

Fix newrelic activation in jormungandr

---

templates/jormungandr/settings.py.jinja

Fix Newrelic

---

fabfile/instance.py
templates/kraken/kraken.ini.jinja

To allow use of https://github.com/CanalTP/navitia/pull/2581
TODO:

Add enable_realtime_add option to instance

---

static_files/ed/default_synonyms.txt

https://jira.kisio.org/browse/NAVITIAII-2623

add a synonym for "c.cial"

---

fabfile/component/jormungandr.py
fabfile/instance.py
tests/tests_instance.py

Add the ability to configure per instance, a list of equipment providers.

Add equipment details providers to bt set per instance

---

templates/jormungandr/settings.py.jinja

This is a requirement to deliver real time equipment reports for Sytral. 
This adds the ability to configure the equipment providers from navitia deployment configuration.

Add EQUIPMENT_DETAILS_PROVIDERS configuration to jormun's settings.py

---

fabfile/component/load_balancer.py

check if is the active F5 who is configured.

add check F5 active-passive F5

---

templates/jormungandr/settings.py.jinja

https://jira.kisio.org/browse/DEVOPP-2457

Add params ZMQ_DEFAULT_SOCKET_TYPE to jormungandr settings.py

---

requirements.txt

Github check CVE vulnerability
- https://github.com/CanalTP/fabric_navitia/network/alerts
I update versions for  delivery customer.

Fix alerts github to requirements

---

scripts/retreive_debian_packages_from_github.py

We recently had an error when trying to deploy Navitia on Artemis saying:
```sh
[artifacts.zip]
End-of-central-directory signature not found.  Either this file is not
a zipfile, or it constitutes one disk of a multi-part archive.  In the
latter case the central directory and zipfile comment will be found on
the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of artifacts.zip or
artifacts.zip.zip, and cannot find artifacts.zip.ZIP, period.
Build step 'Execute shell' marked build as failure
```
The problem actually came from an archive not properly downloaded.  `wget` (the python library used for downloading) does not seem to raise any error when an issue occurs. 
I wanted to make sure that the downloaded file size is the same one as the one coming from Github's …

Check file size when downloading artifact from github

---

scripts/retreive_debian_packages_from_github.py

we can use the run_number to find the latest build

use run_number to retrieve the latest build

---

scripts/retreive_debian_packages_from_github.py

Handl when multi artifacts are present...
Ex: https://github.com/CanalTP/navitia/actions/runs/355479021
https://jira.kisio.org/browse/NAVP-1684

[NAV2][Scripts][>8.0] Handle multi artifacts

---

scripts/retreive_debian_packages_from_github.py

Reverts CanalTP/fabric_navitia#314

Revert "[NAV2][Scripts][>8.0] Handle multi artifacts"

---

.jenkins/deploy_navitia

Issue: Before, it was all minutes...

[jenkins] Fix cron for jenkins deploy

---

.jenkins/deploy_navitia

Available:
- Artemis Job
- Artemis Job nightly

[Jenkins] deploy on Artemis machine

---

.jenkins/publish_navitia_packages

The job : https://github.com/CanalTP/jenkins_conf/pull/97

[Jenkins] Publish navitia debian packages

---

.jenkins/deploy_navitia

A simple `build job: 'artemis_old', wait: false` run artemis old... Easy :gun: 
related job : https://github.com/CanalTP/jenkins_conf/pull/103

[jenkins] Trig old artemis after a deploy on artemis machine

---

.jenkins/publish_navitia_packages

Send a message when Navitia Debian Package are available on devOps machine.
It is interesting to alert team when the process release is complete

[Jenkins] Send a message when Navitia Debian Package are available on devOps machine

---

.jenkins/publish_navitia_packages

Update path with the new hash -> https://github.com/CanalTP/jenkins_conf/pull/111

[jenkins] Fix debian8 path

---

fabfile/env/platforms.py

Jira: [NAVITIAII-3517](https://jira.kisio.org/browse/NAVITIAII-3517)

[NAV2][ALL][>=10] Change timeout bragi

---

fabfile/env/platforms.py

Reverts CanalTP/fabric_navitia#336

Revert "[NAV2][ALL][>=10] Change timeout bragi"

---

fabfile/env/platforms.py

Jira: [NAVITIAII-3584](https://jira.kisio.org/browse/NAVITIAII-3584)

[NAV2][ALL][>=12.2.1] Change TIMEOUT_TIMEO(60s to 15s)
