CanalTP/fabric_navitia

- fabfile/env/platforms.py
- templates/jormungandr/settings.py.jinja
In production we have 80 connections to the database, and they are
almost never used since we cache all call to the database, and we don't
have a lot of data in it, only configuration of the instances and
authentication
> We want to be able to limit the number of connection to the database

- fabfile/custom_tasks.py
- fabfile/env/platforms.py
- fabfile/utils.py
now you can do:
`fab  use:artemis packages:"https://ci.navitia.io/job/navitia_release_multi_os/LINUX_DISTRIB\=debian8/lastSuccessfulBuild/artifact/*zip*/archive.zip" version`
to install the last packages
and :
`fab  use:artemis let:debian_packages_path=/tmp/navitia_packages_20160115-140324797357
upgrade_version`
to install packages already downloaded (in they are stored in
/tmp/navitia_pacakges_{datetime}
> change a bit the get_packages task

- templates/tyr/tyr_worker.jinja
http://docs.celeryproject.org/en/latest/userguide/optimizing.html
TLDR: we don't want to prefect a lot of message since they will wait
really long for the previous task to finish.
We should wait after the next deployment to prod for merging this PR, it would be nice to test a little on internals platforms.
> Use the fair optimization profile of celery

- templates/jormungandr/jormungandr.wsgi.jinja
linked to http://jira.canaltp.fr/browse/NAVITIAII-2047
the import of _strptime does not seems to be thread safe
(http://bugs.python.org/issue7980), so it has to be done before threads
start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/canaltp/fabric_navitia/108)
> try to fix thread bug

- fabfile/component/kraken.py
- integration_tests/test_kraken/test_duplicated.py
because someone can mistakenly call restart_all_kraken with an instance name as positional parameter and this would restart all kraken in prod in parallel, which would result in a massive and general service outage !!!
> fix restart_kraken robustness against wrong wait parameter

- fabfile/tasks.py
The artemis's deployment uses the "upgrade_version" task which calls "upgrade_tyr" task. This one reload apache by default but if apache is not started before, the task fails.
> fix deployment artemis

- fabfile/component/jormungandr.py
- fabfile/component/tyr.py
- fabfile/tasks.py
- fabfile/utils.py
restart = stop + start
reload = remain running + re-read configuration files
"graceful" is better than "reload" because it is waiting the process is finished but need "restart" to kill old process. 
To be sure to restart the service, it is better to stop and start it.
> Fix deployment

- templates/jormungandr/settings.py.jinja
for coherence the params name have been changed by
https://github.com/CanalTP/navitia/pull/1911
Note: since the conf have not been really deployed for the moment, we
accepted a non retrocompatible change
> update jormungandr configuration

- templates/tyr/settings.py.jinja
Activate https://github.com/CanalTP/navitia/pull/2068 to have a job id to follow/filter in logs
Might break regex used in Kibana (logstash file)
So Navitia team may only approve.
Devops team will (remove `do_not_merge` tag and ) merge whenever they're ready ( @chbiguereau @Hoshiyo )
> add task id to log

- fabfile/env/platforms.py
- templates/jormungandr/settings.py.jinja
https://uwsgi-docs.readthedocs.io/en/latest/Caching.html
Once activated this cache add a first layer used **before** redis that is shared between all the processes of an host. 
This will sightly increase performance but mostly reduce the number of call to redis.
> Add configuration to jormungandr for using uwsgi cache

- fabfile/tasks.py
For the deployment on Artemis, restarting services causes issues as Krakens don't have any data yet. This PR will allow Jenkins to upgrade the conf on Artemis without failure.
Note:
The job 'deploy_navitia_on_artemis' has been updated as follow:
```PYTHONPATH=/etc/navitia_deployment_conf/ python -u -m fabric use:artemis update_all_configurations:restart=False```
> Conditional restart of services

- templates/jormungandr/settings.py.jinja
This logger writes to stdout.
When jormun is launched by uswgi these log are caught by uwsgi and
write to the log file configured in it.
By itself this PR doesn't do anything as this new handler won't be used
until `env.jormungandr_default_handler` is set.
> Add another handler for logging in jormungandr

- fabfile/env/platforms.py
The default values added for the dedicated rabbimq stats will break for the environements with no separated Rqbbitmq (like `Dev`).
This PR set the default values back to what they were.
> Set Rabbimq with default original ones

- fabfile/env/platforms.py
- templates/tyr/instance.ini.jinja
- templates/tyr/settings.py.jinja
Celery and Kraken are using Rabbimq, but for complete different purpose.
The service used to be hosted on the exact same machine, which is not
the case anymore.
Hence the need to address 2 different brokers:
* One for Tyr to interact with Celery: CELERY_BROKER_URL
* One for Tyr to interact with the Krakens: KRAKEN_BROKER_URL
> [Tyr] Split brokers used for Celery and Kraken

- scripts/README.md
- scripts/requirements.txt
- scripts/retreive_debian_packages_from_github.py
This script is capable to download the **last artifact** linked to a job, if the job is **in success.**
It is saved inside navitia fabric because we want to use it in adequacy with the fabric.
The deploy needs Navitia Debian packages Artifacts (from **Github Actions**) and it can provide it.
**Example**
In our context, we can use it like this : 
- replace in the _deploy_navitia_on_dev_ Jenkins job, the :
by the following command line :
```
python2.7 retreive_debian_packages_from_github.py -u jenkinsctp -t GITHUB_TOKEN -w "Build Navitia Packages" -a artifacts.zip -o "./.."
```
we directly download the artifacts from https://github.com/CanalTP/navitia/actions?query=workflow%3A%22Build+Navitia+Packages%22
the trace
```
2020-03-03 09:47:10,610 - retreive debian package from github - INFO - …
```
> Github Actions: Retreive the last Navitia Debian packages in success

- fabfile/component/kraken.py
Set timeout value to 5 instead of 2
> timeout error HTTPConnectionPool - Read timed out. (read timeout=2)

- fabfile/component/kraken.py
In the task `get_not_loaded_instances_per_host() ` the result of the request to kraken-monitor can be `{"error": ["instance invalid"]}` (see [here](https://github.com/CanalTP/navitia/blob/f48e96b6cc20bdf4916e3af4a497e15db6e11b25/source/monitor/monitor_kraken/app.py#L58)), and when this happens the task crash.
This PR aims at handling this case without crashing.
> Do not crash on invalid kraken instance 

- requirements.txt
As Jinja and Jinja2 are now **very** separate :
* `Jinja` holds versions < 2
* `Jinja2` versions >= 2.
Review carefully: Dont know why both were required (and what could break).
Another solution is to step back to Jinja==1.2 (last version), reverting part of https://github.com/CanalTP/fabric_navitia/pull/304
My suggestion:
* Merge it before any deployment not-on-prod, let dev nightly deploy test it, then use it for not_on_prod deployment.
* If anything breaks, go back to `Jinja==1.2` and look for a better solution after.
> [NAV2] [ALL] [>=8.2] Naive fix of Jinja requirements breaking

- .jenkins/deploy_navitia
- requirements.txt
Add a new jenkins pipe to deploy Navitia on Dev with the new Jenkins CI.
It was a lonng road to arrive here with many obstacles.
Now it works !
- With a docker environment for avoiding to pollute de agent machine. Ubuntu 18.0' and not 20.04 because of specific python 2 libraries. Not with a classic python2 imagine because we need more for other action unzip, curl, etc...
- Add a cron trigger to be compliant with the job https://ci.navitia.io/job/deploy_navitia_on_dev_from_github/ in the old CI. The deploy on Dev is during the night
- Use an external script to retreive debian packages from github actions https://github.com/CanalTP/navitia/actions?query=workflow%3A%22Build+Navitia+Packages+For+Dev+Multi+Distributions%22
- Ready to use a dev debian10 platform when it will be ready poke …
> [JenkinsPipe] core team - deploy navitia jenkins pipe

- .jenkins/publish_navitia_packages
Simple issue : Choose the good Github Actions  job to publish (this is release packages)
> [Jenkins] Choose the good GA job to publish

- .jenkins/deploy_navitia
It was an issue when a Pull request job was running. There was collision. 
The option already exist.
> Jenkins: deploy only with dev branch debian packages

- .jenkins/publish_navitia_packages
We need to wait until the GA job to create packages has finish (we trig the jenskins job but sometimes debian10 or debian 9 have not finish)
The option already exists inside  `python core_team_ci_tools/github_artifacts/github_artifacts.py` script.
We just need to active the option for release branch
> CI: waiting GA job to load packages

- .jenkins/deploy_navitia
The problem appears if we merge rapidly 2 PR. 
At the end of the first building package, we launch a deploy on Artemis but the last building packet job is under progress, so the deploy failed.
With the waiting option it'll be not a problem
> [Jenkins] Wait to deploy if package is under progress

- fabfile/component/kraken.py
- requirements.txt
* While deploying navitia, loads all krakens of each coverage(instance) in parallel. 
* This PR can be merged and used to test while deploying navitia in the platforms like internal, customer..
* If success Bingo
* If not rollback this PR and continue the corrections...
Concerned ticket : https://jira.kisio.org/browse/NAVP-1777
> [NAV2][ALL] Load all krakens of each instance in parallel

- fabfile/component/kraken.py
- requirements.txt
Due to issues on deployment, for production, we will revert.
Once deployed in production, we will re-revert again, in order to let @kadhikari work on improvments
> Revert "[NAV2][ALL] Load all krakens of each instance in parallel"

- fabfile/component/kraken.py
- requirements.txt
* While deploying navitia
** stop and start all kraken services for each instance(coverage) in serial mode.
** calls and verifies one kraken per instance(coverage) with instances in parallel.
** Already tested to reload some coverages in customer in debug mode.
** Already tested to deploy in the platform dev.
* This PR can be merged and used to test while deploying navitia in the platforms like internal, customer..
* If success Bingo
* If not rollback this PR and continue the corrections...
Concerned ticket : https://jira.kisio.org/browse/NAVP-1777
Relates to https://github.com/CanalTP/fabric_navitia/pull/332
> [NAV2][ALL]: Call all krakens in parallel

- .jenkins/publish_navitia_packages
Fix the issue
```
09:59:30  Package python-pip is not available, but is referred to by another package.
09:59:30  This may mean that the package is missing, has been obsoleted, or
09:59:30  is only available from another source
09:59:30  However the following packages replace it:
09:59:30    python3-pip
09:59:30  
09:59:30  E: Package 'python-pip' has no installation candidate
```
> [CI] - fix navitia packages publishing

- fabfile/component/kraken.py
- requirements.txt
For verification, kraken.py should be as in the version : https://github.com/CanalTP/fabric_navitia/blob/5dee8d029d5c527c7f65db03bb351d8341e166bc/fabfile/component/kraken.py
This corresponds to the correction of @pbench committed on 14 Oct 2020
https://github.com/CanalTP/fabric_navitia/commits/5dee8d029d5c527c7f65db03bb351d8341e166bc/fabfile/component/kraken.py
> [PROD]: Revert Call all krakens in parallel

- .jenkins/deploy_navitia
We now rely on Artemis_NG to perform Navitia's integration tests, so triggering Artemis_Old is not needed anymore.
> [CI] do not trigger artemis_old after deploy
